### ISSUE TITLE
[BUG]:  require-usememo checkHookReturnObject option evaluates non-hook functions

### ISSUE THREAD

**Issue by michael1997** [arthurgeron/eslint-plugin-react-usememo#32]
## Prerequisites

- [x] Before you create a new issue, please ensure that this is not a duplicate issue and that you have gone through all the debugging steps.

## Minimal repro

Please provide a minimal piece of code or reproducible example that demonstrates the issue.  

The require-usememo rule shows a lint error on functions that are not hooks using the checkHookReturnObject option.

```javascript
// use-memo rule alerts an error but this is not a hook
function userTest() {
  return {};
}

// works as expected - suggests a useMemo
function useTest() {
  return {};
}

``````   
> Some rules process import statements. Make sure to include them if they're relevant to this issue.

### Installed packages versions
**ESLint:**    eslint@8.33.0
**Eslint-plugin-react-usememo:** @arthurgeron/eslint-plugin-react-usememo@2.2.1

### Rule and its options

Which rule from the eslint-plugin-react-usememo is being used? What configuration options are set for this rule?

```
"@arthurgeron/react-usememo/require-usememo": ["error", {
      "strict": false,
      "checkHookReturnObject": true,
      "fix": { "addImports": false },
      "checkHookCalls": false
    }],
```
### Error log / Stack trace

Please provide the full error log or stack trace, if any.

N/A

**Comment by arthurgeron** [comment]
Fixed in v2.2.2. Thank you for reporting this.
