### ISSUE TITLE
Missing readme.md on npmjs

### ISSUE THREAD

**Issue by SimonSchick** [arthurgeron/eslint-plugin-react-usememo#42]
See https://www.npmjs.com/package/@arthurgeron/eslint-plugin-react-usememo is practically blank, which is strange since npm will generally always publish the readme file, maybe LumaKernel/npm-release-pack-action is broken?

**Comment by SimonSchick** [comment]
Weirdly enough now it shows, maybe intermittend downtime on npmjs end? It didn't seem to affect any other packages.

Proof I'm not making this up:
<img width="981" alt="image" src="https://github.com/arthurgeron/eslint-plugin-react-usememo/assets/3259089/8d204fcd-c9f0-4e72-acc3-3a6f3885066f">

**Comment by arthurgeron** [comment]
@SimonSchick You're not crazy, I've seen that issue myself!  I've no idea what might be wrong but I'm pretty sure it's on their side. 
NPM.js automatically uses the README.md at the root of the project but, for some weird reason, it might not display on some accesses to the lib's page on their domain. Refreshing seems to temporarily "fix" the issue.

Regardless, thank you for taking your time to report this here, I hope they eventually fix the ongoing issue.
